#!/usr/local/bin/python3

import os
import sys

target = sys.argv[1]
target_bk = target + '_backup' if os.path.isdir(path) else target + '.bak'

if os.path.exists(target_bk):
    choice = input('backup file already exists, delete it? (Y/n)').strip()
    if choice == 'Y' or choice == '':
        os.system(f'rm -rf {target_bk}')
    else:
        print('abort')
        exit(0)

os.system(f"cp -r {target} {target_bk}")