#!/usr/local/bin/python3
import requests as r
from lxml import etree
import os
import argparse

j = os.path.join
parser = argparse.ArgumentParser(
    description="make your clone EASY!",
    usage="clone [-*] [repo] [dest]"
)
parser.add_argument('-s','--self',  action="store_true", help="get your own repos")
parser.add_argument('-d','--direct',action="store_true", help="directly clone")
parser.add_argument('-f','--follow',action="store_true", help="follow 2 dest")
parser.add_argument("repo",help="repo_name",type=str)
parser.add_argument("dest",help="destination",type=str,nargs='?',default="")
args = parser.parse_args()


def clone(url):
    path = j(args.dest, url.split('/')[-1])
    
    os.system(' '.join([url,path]))


if args.self: # --self
    clone(f"git clone https://github.com/you-bowen/{args.repo}")
else:
    url = f'https://github.com/search?q={args.repo}'

    resp = r.get(url).text
    html = etree.HTML(resp)

    results = []
    for i in range(1,6):
        ele = html.xpath(f'//*[@id="js-pjax-container"]/div/div[3]/div/ul/li[{i}]/div[2]/div[1]/div[1]/a/@href')
        try:
            results.append(ele[0])
        except:
            break
    if args.direct:
        res = results[0]
    else:
        for id,i in enumerate(results):
            print(f"{id}. {i}")
        choice = input(f"clone 0st by default({results[0]}):")
        res = results[int(choice)] if choice!="" else results[0]
    
    clone(f"git clone https://github.com{res}")