#!/usr/bin/python3
import requests as r
from lxml import etree
import os
import argparse

parser = argparse.ArgumentParser(
    description="make your clone EASY!",
    usage="clone [-*] [repo]"
)
parser.add_argument('-s','--self',  action="store_true", help="get your own repos")
parser.add_argument('-d','--direct',action="store_true", help="directly clone")
parser.add_argument("repo",help="repo_name",type=str)
args = parser.parse_args()


if args.self: # --self
    os.system(f"git clone https://github.com/you-bowen/{args.repo}")
else:
    url = f'https://github.com/search?q={args.repo}'

    resp = r.get(url).text
    html = etree.HTML(resp)

    results = []
    for i in range(1,6):
        j = html.xpath(f'//*[@id="js-pjax-container"]/div/div[3]/div/ul/li[{i}]/div[2]/div[1]/div[1]/a/@href')
        results.append(j[0])

    if args.direct:
        res = results[0]
    else:
        for id,i in enumerate(results):
            print(f"{id}. {i}")
        choice = input(f"clone 0st by default({results[0]}):")
        res = results[int(choice)] if choice!="" else results[0]
    
    os.system(f"git clone https://github.com{res}")