#!/usr/local/bin/python
import webbrowser
import sys

def parsePort(port: str):
    if port == "":
        return "80"
    elif port.endswith("k"):
        return str(int(port[:-1]) * 1000)
    else:
        return port
port = sys.argv[1]
port = parsePort(port)
webbrowser.open(f"http://localhost:{port}")
