#!/usr/local/bin/python3

import os
import sys

target_bk = sys.argv[1]
if not (target_bk.endswith('.bak') or target_bk.endswith('_backup')):
    print("format error!")
    sys.exit(0)
target = target_bk.replace('.bak','').replace('_backup','')
if os.path.exists(target):
    os.system(f'rm -rf {target}')
os.system(f'cp -r {target_bk} {target}')
    